version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - '27017:27017'
  inbound-saml:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    container_name: inbound-saml
    ports:
      - '5000:5000'
    depends_on: 
      - mongo
    links:
      - mongo
