version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    ports:
      - '27017:27017'
  # inbound-saml:
  #   build: 
  #     context: .
  #   volumes:
  #     - ./:/code
  #   depends_on: 
  #     - mongo
