version: '2'
services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      CONTAINER_LOG_LEVEL: 0
      LDAP_LOG_LEVEL: "-1"
      LDAP_ORGANISATION: "gluu"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_DOMAIN: "gluu"
    # command: --copy-service --loglevel debug
    # volumes:
      # - ./schemas:/container/service/slapd/assets/config/bootstrap/schema/custom
      # - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

    stdin_open: true
    ports:
      - "389:389"
      - "636:636"
    depends_on:
      - inbound-saml
  
  inbound-saml:
    build: 
      context: .
    volumes:
      - ./:/code
