# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      - node/test:
          version: '14.17.4'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
  build:
    jobs:
      - build

jobs:
  build:
    machine: true
    steps:
      # Docker is preinstalled, along with docker-compose
      - checkout

      # start proprietary DB using private Docker image
      - run: |
          docker-compose up
          npm run test
          
        # docker login -u $DOCKER_USER -p $DOCKER_PASS
        # docker run -d --name db company/proprietary-db:1.2.3

